version: '1.0'
name: main-pipeline
displayName: main-pipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
variables:
  DOCKER_IMAGE: p9t.io/kuberboat/ci:1.0.0
  DOCKER_CONTAINER: kuberboat-ci-test
  TEST_FMT_PATH: ./test/test_fmt.sh
stages:
  - name: container
    displayName: Create Container
    strategy: fast
    trigger: auto
    steps:
      - step: shell@agent
        name: create-container
        displayName: create container
        hostGroupID: test
        script: |-
          docker ps -q --filter "name=${DOCKER_CONTAINER}" | grep -q . && docker stop ${DOCKER_CONTAINER} && docker rm ${DOCKER_CONTAINER}
          docker run --privileged -d -t --name ${DOCKER_CONTAINER} ${DOCKER_IMAGE}
  - name: clone
    displayName: Clone Repo
    strategy: fast
    trigger: auto
    steps:
      - step: shell@agent
        name: clone
        displayName: Clone Repo
        hostGroupID: test
        script: |-
          docker exec ${DOCKER_CONTAINER} bash -c '\
            git clone git@gitee.com:xx01cyx/kuberboat.git; \
            cd ${GITEE_REPO}'
          if [ $? -ne 0 ]
          then exit 1
          fi
  - name: test
    displayName: Test
    strategy: naturally
    trigger: auto
    steps:
      - step: shell@agent
        name: format
        displayName: Test Format
        hostGroupID: test
        script: |-
          docker exec ${DOCKER_CONTAINER} bash -c '\
            cd ${GITEE_REPO}; \
            chmod +x ${TEST_FMT_PATH}; \
            ./${TEST_FMT_PATH}'
          exit $?
      - step: shell@agent
        name: build
        displayName: Test Build
        hostGroupID: test
        script: |-
          docker exec ${DOCKER_CONTAINER} bash -c '\
            cd ${GITEE_REPO}; \
            make'
          exit $?
permissions:
  - role: admin
    members: []
