version: '1.0'
name: pr-ci-test
displayName: pr-pipeline-test
triggers:
  trigger: auto
  push:
    branches:
      exclude:
        - main
  pr:
    branches:
      precise:
        - main
variables:
  REPO_NAME: kuberboat
  TEST_FMT_PATH: ./test/test_fmt.sh
  START_STANDALONE_PATH: ./scripts/kuberboat/start_standalone.sh
  STOP_STANDALONE_PATH: ./scripts/kuberboat/stop_standalone.sh
  TEST_ALL_PATH: ./test/kuberboat/test_all.sh
stages:
  - name: kuberboat-ci-test
    displayName: CI Test
    strategy: fast
    trigger: auto
    steps:
      - step: shell@agent
        name: test-fmt
        displayName: Format Test
        hostGroupID: test
        script: |-
          export PATH=$PATH:/usr/local/go/bin
          export PATH="$PATH:$(go env GOPATH)/bin"
          git clone -b ${GITEE_SOURCE_BRANCH} git@gitee.com:xx01cyx/kuberboat.git
          cd ${REPO_NAME}
          if [ $? -ne 0 ]
            then exit 1
          fi
          chmod +x ${TEST_FMT_PATH}
          ./${TEST_FMT_PATH}
          cd .. && rm -rf ${REPO_NAME}
      - step: shell@agent
        name: test-function
        displayName: Functional Test
        hostGroupID: test
        script: |-
          export PATH=$PATH:/usr/local/go/bin
          export PATH="$PATH:$(go env GOPATH)/bin"
          git clone -b ${GITEE_SOURCE_BRANCH} git@gitee.com:xx01cyx/kuberboat.git
          cd ${REPO_NAME}
          if [ $? -ne 0 ]
            then exit 1
          fi
          chmod +x ${START_STANDALONE_PATH}
          chmod +x ${STOP_STANDALONE_PATH}
          chmod +x ${TEST_ALL_PATH}
          ./${START_STANDALONE_PATH}
          ./${TEST_ALL_PATH}
          ./${STOP_STANDALONE_PATH}
          cd .. && rm -rf ${REPO_NAME}
permissions:
  - role: admin
    members: []
