kind: Deployment
metadata:
  name: deployment-version
spec:
  replicas: 8
  rollingUpdate:
    maxSurge: 2
    maxUnavailable: 5
  template:
    metadata:
      labels:
        app: my-version
        env: dev
    spec:
      containers:
      - name: version_server
        image: windowsxpbeta/http_server:v2.0
        ports: 
          - 8080
